In [1]:
import numpy as np



In [ ]:
a= np.arange(12).reshape(4,3)
print(a)#

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [4]:
#Indexing
#change value 10 from above
a[3,1]=20
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 20 11]]


In [5]:
import sklearn

In [6]:
import math
import matplotlib.pyplot as plt

In [7]:
a=np.arange(10) 

In [8]:
a_summ=np.sum(a)
print(a_summ)

45


In [9]:
a_sin=np.sin(a)
print(a_sin)

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [11]:
#working with sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
b=np.arange(10)
sigmoid(b)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])