In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
%pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 3.4 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/12.8 MB 3.3 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.8 MB 3.3 MB/s eta 0:00:04
   ------- -------------------------------- 2.4/12.8 MB 3.0 MB/s eta 0:00:04
   --------- ------------------------------ 3.1/12.8 MB 3.1 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.8 MB 3.1 MB/s eta 0:00:03
   ------------- -------------------------- 4.5/12.8 MB 3.1 MB/s eta 0:00:03
   --------------- ------------------------ 5.0/12.8 MB 3.1 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.8 MB 3.1 MB/s eta 0:00:03
   ------------------- -------------------- 6.3/12.8 MB 3.1 MB/s eta 0:00:03
   ---------------------- ----------------- 7.1/12.8 MB 3.1 MB/s eta 0:00:02
   ----------------------- ---------------- 7.6/12.8 MB 3.1 MB/s eta 0:00:02
   ---

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
numpy --version

NameError: name 'numpy' is not defined

In [7]:
np.__version__

'2.3.5'

In [9]:
array = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
array.reshape(2, 5)
print(array.reshape(2, 5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
#important commandds)
#1. arrange command
#2. reshape command 
#3. linspace command
#4.random command

In [23]:
new_array = np.arange(12,24)
print(new_array)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [27]:
nrray = new_array.reshape(6,2)
print(nrray)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [28]:
# Linspace command
lin_arr_1 = np.linspace(0, 10, 5)
print(lin_arr_1)

[ 0.   2.5  5.   7.5 10. ]


In [30]:
lin_arr_2 = np.linspace(1, 20, 5)
print(lin_arr_2)

[ 1.    5.75 10.5  15.25 20.  ]


In [31]:
#working with random command
random_array = np.random.rand(3, 4)
print(random_array)

[[0.03922108 0.77590045 0.84859598 0.52118084]
 [0.05310937 0.44170775 0.10363304 0.1268809 ]
 [0.25939072 0.90871078 0.39396917 0.24045143]]
