In [1]:
import numpy as np

In [2]:
first_array = np.array([1, 2, 3, 4, 5])
print("Original array:", first_array)

Original array: [1 2 3 4 5]


In [3]:
Second_array_int = np.array([12,13,14], dtype=int)
print("Array with integer data type:", Second_array_int)

Array with integer data type: [12 13 14]


In [6]:
#performing scalar operations
a=np.array([5])
print(a)

[5]


In [7]:
#adding numbers to scalar
print(a+10)

[15]


In [8]:
# when we add scalar to another scalar, the result is also a scalar
# when we add scalar to vector, the result is also a vector
# when we multiply scalar to vector, the result is also a vector

In [9]:
#vector operations
first_vector = np.array([1, 2, 3])
second_vector = np.array([4, 5, 6])
print(first_vector + second_vector)
print(first_vector * second_vector)
print(first_vector - second_vector)
print(first_vector / second_vector)

[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]


In [11]:
# Array multiplication (when we do element-wise multiplication)
result_vector = np.multiply(first_vector, second_vector)
print(result_vector)

[ 4 10 18]


In [14]:
# Concept which is called matrix operations.
first_matrix= np.array([[1,2,3],[4,5,6]])
second_matrix= np.array([[7,8,9],[10,11,12]])
print(first_matrix + second_matrix)
print(first_matrix / second_matrix)
print(first_matrix - second_matrix)

[[ 8 10 12]
 [14 16 18]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[-6 -6 -6]
 [-6 -6 -6]]


In [16]:
#matrix multiplication (when we do matrix multiplication)
#Rules of matrix multiplication:
#1. The number of columns in the first matrix must be equal to the number of rows in the second matrix.
first_matrix = np.array([1,2,3])
second_matrix = np.array([1,2,3])
result_matrix = np.matmul(first_matrix, second_matrix)
print(result_matrix)
#2. The resulting matrix will have the same number of rows as the first matrix and the same number of columns as the second matrix.

14


In [18]:
result_matrix = np.multiply(first_matrix, second_matrix)
print(result_matrix)


[1 4 9]


In [25]:
third_matrix = np.array([[1, 2, 3],[4, 5, 6]])
fourth_matrix = np.array([[7, 8],[10, 11], [12,13]])
array_product = np.matmul(third_matrix, fourth_matrix)
print(array_product)


[[ 63  69]
 [150 165]]


In [26]:
transposed_matrix = np.transpose(fourth_matrix)
print(transposed_matrix)

[[ 7 10 12]
 [ 8 11 13]]


In [28]:
# for normal vectors and matrices, the operations are performed element-wise
# but for special types of vectors and matrices, the operations are different
# what are those special types?
# 1. Sparse matrices
# 2. Diagonal matrices
# 3. Identity matrices
# 4. Orthogonal matrices
# These special types of matrices have their own rules for operations like addition, multiplication, etc.       
# For example, in the case of sparse matrices, only the non-zero elements are stored and operated upon, which saves memory and computation time.
# Similarly, diagonal matrices have non-zero elements only on the main diagonal, and identity matrices have ones on the main diagonal and zeros elsewhere.
# --- IGNORE ---
#Dot product of two vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
dot_product = np.dot(vector_a, vector_b)
print("Dot product of vector_a and vector_b:", dot_product)
# --- IGNORE ---
# what are types of multiplication like dot product, cross product, etc.
# Dot product is the sum of the products of the corresponding entries of the two sequences of numbers.
# Cross product is a binary operation on two vectors in three-dimensional space and is denoted by the symbol ×.
# The cross product of two vectors results in a third vector which is perpendicular to the plane containing the first two vectors.
# --- IGNORE ---
#examples of special matrices
# Sparse matrix
sparse_matrix = np.array([[0, 0, 3], [4, 0, 0], [0, 0, 0]])
print("Sparse Matrix:\n", sparse_matrix)
# Diagonal matrix
diagonal_matrix = np.diag([1, 2, 3])
print("Diagonal Matrix:\n", diagonal_matrix)
# Identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)
# Orthogonal matrix
orthogonal_matrix = np.array([[1, 0], [0, -1]])
print("Orthogonal Matrix:\n", orthogonal_matrix)
# --- IGNORE ---





Dot product of vector_a and vector_b: 32
Sparse Matrix:
 [[0 0 3]
 [4 0 0]
 [0 0 0]]
Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Orthogonal Matrix:
 [[ 1  0]
 [ 0 -1]]
